name: Build Flatpak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install flatpak and flatpak-builder
        run: |
          sudo apt update
          sudo apt install -y flatpak flatpak-builder p7zip-full
      
      - name: Download Unity Linux build
        env:
          BUILD_URL: "https://builds.orbprojectmanagement.com/Linux/Build_Linux.zip"
        run: |
          curl -fL "$BUILD_URL" -o Build_Linux.zip
          if [ $(stat --printf="%s" Build_Linux.zip) -lt 1048576 ]; then
            echo "::error::Downloaded ZIP is too small to be valid." >&2
            exit 1
          fi

      - name: Download icon PNG directly
        run: curl -fL https://builds.orbprojectmanagement.com/Images/Logo.png -o icon.png

      - name: Prepare Flatpak files
        run: |
          mkdir -p flatpak
          cp Build_Linux.zip flatpak/
          cp icon.png flatpak/
          cp com.orbprojectmanagement.OrbProject.yml flatpak/
          cp com.orbprojectmanagement.OrbProject.desktop flatpak/

      - name: Install Flatpak and SDK
        run: |
          sudo apt update
          sudo apt install -y flatpak flatpak-builder
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install -y flathub org.freedesktop.Sdk//23.08 org.freedesktop.Platform//23.08

      - name: Build Flatpak
        working-directory: flatpak
        run: |
          flatpak-builder --force-clean --repo=repo build-dir com.orbprojectmanagement.OrbProject.yml
          flatpak build-bundle repo OrbProject.flatpak com.orbprojectmanagement.OrbProject

      - name: Upload Flatpak artifact
        uses: actions/upload-artifact@v4
        with:
          name: OrbProject.flatpak
          path: flatpak/OrbProject.flatpak 
