name: Flatpak Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flatpak and Builder
        run: |
          sudo apt update
          sudo apt install -y flatpak flatpak-builder libfuse2 wget

      - name: Add Flathub remote
        run: flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Download AppImage and extract
        run: |
          mkdir -p files/orbproject
          wget https://github.com/OrbProject/OrbProjectLinux/releases/latest/download/OrbProject-v*-x86_64.AppImage -O OrbProject.AppImage
          chmod +x OrbProject.AppImage
          ./OrbProject.AppImage --appimage-extract
          cp -r squashfs-root/* files/orbproject/
          chmod +x files/orbproject/AppRun

      - name: Build Flatpak
        run: |
          flatpak install -y flathub org.freedesktop.Sdk//23.08 org.freedesktop.Platform//23.08
          flatpak-builder --user --force-clean build-dir com.orbprojectmanagement.OrbProject.yml

      - name: Export Flatpak
        run: |
          flatpak build-export repo build-dir
          flatpak build-bundle repo OrbProject.flatpak com.orbprojectmanagement.OrbProject

      - name: Upload Flatpak artifact
        uses: actions/upload-artifact@v4
        with:
          name: OrbProject.flatpak
          path: OrbProject.flatpak

